---
title: "上海新冠疫情概况"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    css: my-custom-rules.css
    theme: readable
    navbar:
      - { title: "居住地信息", href: "https://covid-sh-6gkhr9773dab473d-1257749604.ap-shanghai.app.tcloudbase.com/map", align: right }
    source_code: "https://github.com/shalom-lab/covid.sh/blob/main/local/index.Rmd"

---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
source('./code-plot.R',encoding='utf-8')
source('./code-rt.R',encoding='utf-8')
```


# 全市

Row {data-height=200}
--------------------------------------------------------------------

### 昨日新增确诊
```{r}
valueBox(count.new.case, icon = "fa-comments",color="info")
```

### 昨日新增无症状
```{r}
valueBox(count.new.asym, icon = "fa-comments",color="danger")
```

### 昨日净增阳性感染人数
```{r}
valueBox(count.new.pos_real, icon = "fa-comments",color="primary")

```

### 累计确诊病例(自3月9日起)
```{r}
valueBox(count.cum.case, icon = "fa-comments",color="warning")
```

### 累计阳性感染者(自3月9日起)
```{r}
valueBox(count.cum.pos_real, icon = "fa-comments",color="success")
```


row {data-height=800}
-----------------------------------------------------------------------
### 每日阳性感染者 数据摘自上海发布 更新于 `r format(Sys.time(), "%Y-%m-%d %X")`

```{r}
plot.sh.pos_real
```

### 累计阳性感染者

```{r}
plot.sh.cum_pos_real
```


# 新增及累计

Column {.tabset}
-----------------------------------------------------------------------

###  新增-分区

```{r}
plot.district.new

```

### 累计-分区
```{r}
plot.district.cum
```
###  新增&累计

```{r}
plot.sh.line
```

###  新增&累计

```{r}
plot.sh.bar

```

# 各区情况


Column { .tabset }
-----------------------------------------------------------------------

### 新增

```{r}
plot.timeline.new

```

### 新增构成

```{r}
plot.timeline.new.bar

```

### 累计

```{r}
plot.timeline.cum
```

### 累计构成

```{r}
plot.timeline.cum.bar
```


# 构成情况

    
Row {data-height=500}
-------------------------------------
    
### 新增阳性
    
```{r}
prop.pos.new
```

### 新增病例

```{r}
prop.case.new
```   

### 新增无症状

```{r}
prop.asym.new
```   

Row {data-height=500}
-------------------------------------

### 累计阳性
    
```{r}
prop.pos.cum
``` 

 
### 累计病例
    
```{r}
prop.case.cum
```

### 累计无症状

```{r}
prop.asym.new
```   

<!-- # 居住地信息 -->

<!-- ```{r} -->
<!-- plot.map.location -->

<!-- ``` -->

# 流行趋势

### 时变再生数Rt [阅读原文](https://blog-7gi7tsfg85e1922f-1257749604.ap-shanghai.app.tcloudbase.com/posts/epi/covid-rt.html) { data-width=800 }
```{r}
plot.rt

```

### 系列间隔SI(假设) { data-width=400 }

```{r}
plot.si

```

# 数据

Column { .tabset }
------------------------------------------------

### 变量
```{r}
DT::datatable(variables)
```


### 分区
```{r}
DT::datatable(case.asym.wider,extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```
### 全市
```{r}
DT::datatable(case.asym.wider.sh, extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```
